version: '3'

services:
  nginx:
    image: yosmy/nginx
    container_name: reto_api_nginx
    networks:
      - frontend
      - backend
    working_dir: /var/www
    environment:
      - VIRTUAL_HOST=api.reto.yosmy.com
      - LETSENCRYPT_HOST=api.reto.yosmy.com
      - LETSENCRYPT_EMAIL=contact@reto.yosmy.com
  php:
    image: yosmy/php
    container_name: reto_api_php
    networks:
      - backend
    working_dir: /var/www
    user: "$UID:$GID"
  mongo:
    image: yosmy/mongo
    container_name: reto_api_mongo
    volumes:
      - ../var/db:/data/db
    networks:
      - backend
  imaginary:
    image: h2non/imaginary:1
    container_name: reto_api_imaginary
    user: "$UID:$GID"
    networks:
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true