version: '3'

services:
  nginx:
    volumes:
      - ./nginx/default_dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - frontend
  php:
    volumes:
      - ./php/php_dev.ini:/usr/local/etc/php/php.ini
      - ../:/var/www/
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: "idekey=PHPSTORM remote_host=172.17.0.1"
  mongo:
    ports:
      - 27017:27017
