version: '3'

services:
  nginx:
    volumes:
      - ./nginx/default_prod.conf:/etc/nginx/conf.d/default.conf
    restart: always
  php:
    volumes:
      - ./php/php_prod.ini:/usr/local/etc/php/php.ini
      - ../:/var/www/
    restart: always
  mongo:
    restart: always