reto.http.server.controller_dispatcher:
    class: 'Symsonte\Http\Server\ControllerDispatcher'
    arguments:
        - '@symsonte.service_kit.resource.perpetual_cached_loader'
        - '#symsonte.resource.builder'
        - '@symsonte.service_kit.container'
        - '@symsonte.http.server.request.resolution.nikic_fast_route_finder'
        - '@symsonte.authorization.checker'
        - '@symsonte.http.server.request.authentication.credential.authorization_resolver'
        - '@reto.http.credential_processor'
        - '@reto.http.role_collector'
        - '#symsonte.http.server.convert_parameter'
        - '@reto.http.controller_caller'
        - '@symsonte.http.server'

reto.cli.server.command_dispatcher:
    class: 'Symsonte\Cli\Server\CommandDispatcher'
    arguments:
        - '@symsonte.service_kit.resource.cached_loader'
        - '#symsonte.resource.builder'
        - '@symsonte.service_kit.container'
        - '@symsonte.cli.server.input.resolution.ordinary_finder'
        - '@reto.cli.command_caller'
        - '@symsonte.cli.server'